# The main pipeline for deployment_asset_bundles

resources:
  pipelines:
    deployment_asset_bundles_etl:
      name: deployment_asset_bundles_etl
      catalog: ${var.catalog}
      schema: ${var.schema}
      serverless: true
      root_path: "../src/deployment_asset_bundles_etl"

      libraries:
        - glob:
            include: ../src/deployment_asset_bundles_etl/transformations/**

      environment:
        dependencies:
          # We include every dependency defined by pyproject.toml by defining an editable environment
          # that points to the folder where pyproject.toml is deployed.
          - --editable ${workspace.file_path}
